---
name: Erin
surname: Robinson
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: 
#address: University of Colorado, Information Science Department
position: "Graduate Student | Consultant | Coach"
profilepic: ErinHeadshot.png
#phone: 0996597844
email: erin.robinson-1@colorado.edu
github: erinmr
linkedin: erinmr
orcid: 0000-0001-9998-0114
www: erinrobinson.info
header-includes:
  - \setstretch{1.15}
headcolor: 3b3bc4
output: vitae::awesomecv
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(magrittr)
source("Utils/data_download_funs.R")

CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1QoLsbejLqTdxpQZeED8yNJ6I2-x_WaEjbaaQfLC_pR8/edit?usp=sharing",  
  pdf_mode = FALSE
)
```

\vspace*{0.5cm}
# Research Interests
```{r, results='asis'}
CV %<>% print_text_block("intro") 
```

# Education

```{r, results='asis'}
CV$entries_data %>% 
  filter(section == 'education') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```

# Professional Experience

```{r, results='asis'}
CV$entries_data %>% 
  filter(section == 'industry_positions') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```

# Additional Credentials

```{r, results='asis'}
CV$entries_data %>% 
  filter(section == 'courses') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```

# Awards & Honors

```{r, results='asis'}
CV$entries_data %>% 
  filter(section == 'award') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`}"),
    with = title,
    why = description_bullets
  )
```

# Grants
Additional funding from past positions can be found on [my ORCID profile](https://orcid.org/0000-0001-9998-0114)

```{r, results='asis'}
CV$entries_data %>% 
  filter(section == 'grant') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    why = description_bullets
  )
```

# Selected Publications 
For all publications see my [Google Scholar Profile](https://scholar.google.com/citations?user=PfGu6vEAAAAJ&hl=en&oi=sra) 
```{r}
CV$entries_data %>%
filter(section == 'academic_articles') %>%
detailed_entries(
with = title,
why = description_bullets
)
```

# Service

```{r}
CV$entries_data %>%
filter(section == 'service') %>%
detailed_entries(
with = title,
why = description_bullets
)
```