---
name: Erin
surname: Robinson
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: 
#address: University of Colorado, Information Science Department
position: "Prelim Reading List"
profilepic: ErinHeadshot.png
#phone: 0996597844
email: erin.robinson-1@colorado.edu
github: erinmr
linkedin: erinmr
orcid: 0000-0001-9998-0114
www: erinrobinson.info
header-includes:
  - \setstretch{1.15}
headcolor: 3b3bc4
output: 
  vitae::awesomecv
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(magrittr)
source("Utils/data_download_funs.R")

CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/18GWxmSiUrnKkuzshEAek-gAo68B-c6tNXGbE7a9fz18/edit?usp=sharing",  
  pdf_mode = FALSE
)
```

\vspace*{0.5cm}
# Research Interests
```{r, results='asis'}
CV %<>% print_text_block("intro") 
```

# Theory 
Theory is broken into three parts - STS, Feminist Theory,  
```{r}
CV$entries_data %>%
filter(section == 'academic_articles') %>%
detailed_entries(
with = title,
why = description_bullets
)
```


# Method 
Theory is broken into three parts - STS, Feminist Theory,  
```{r}
CV$entries_data %>%
filter(section == 'academic_articles') %>%
detailed_entries(
with = title,
why = description_bullets
)
```
